name: somatic-variantcalling
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - gatk4==4.0.4.0
#  - strelka==2.9.7
  - vardict==2018.07.25
  - samtools==1.8
#  - manta==1.4.0
  - picard==2.18.11
  - biopet-scatterregions==0.1
  - tabix==0.2.5
  - vardict-java==1.5.4
  - somaticseq==2.8.1